const demos = [
  {
    name: "E-Learning Dashboard",
    screenshotLight: "img/screenshots/dashboard-elearning.png",
    screenshotDark: "img/screenshots/dashboard-elearning-dark.png",
    link: "/dashboard-elearning",
    new: false,
  },
  {
    name: "Accounting Dashboard",
    screenshotLight: "img/screenshots/dashboard-accounting.png",
    screenshotDark: "img/screenshots/dashboard-accounting-dark.png",
    link: "/dashboard-accounting",
    new: false,
  },
  {
    name: "Ecommerce Dashboard",
    screenshotLight: "img/screenshots/dashboard-ecommerce.png",
    screenshotDark: "img/screenshots/dashboard-ecommerce-dark.png",
    link: "/dashboard-ecommerce",
    new: false,
  },
  {
    name: "Domotic Dashboard",
    screenshotLight: "img/screenshots/dashboard-domotic.png",
    screenshotDark: "img/screenshots/dashboard-domotic-dark.png",
    link: "/dashboard-domotic",
    new: false,
  },
  {
    name: "Hosting Dashboard",
    screenshotLight: "img/screenshots/dashboard-hosting.png",
    screenshotDark: "img/screenshots/dashboard-hosting-dark.png",
    link: "/dashboard-hosting",
    new: false,
  },
  {
    name: "Support Dashboard",
    screenshotLight: "img/screenshots/dashboard-support.png",
    screenshotDark: "img/screenshots/dashboard-support-dark.png",
    link: "/dashboard-support",
    new: false,
  },
  {
    name: "Support Ticket",
    screenshotLight: "img/screenshots/content-support-ticket.png",
    screenshotDark: "img/screenshots/content-support-ticket-dark.png",
    link: "/content-support-ticket",
    new: false,
  },
  {
    name: "Datatable",
    screenshotLight: "img/screenshots/content-datatable.png",
    screenshotDark: "img/screenshots/content-datatable-dark.png",
    link: "/content-datatable",
    new: false,
  },
  {
    name: "Contact List",
    screenshotLight: "img/screenshots/content-contact-list.png",
    screenshotDark: "img/screenshots/content-contact-list-dark.png",
    link: "/content-contact-list",
    new: false,
  },
  {
    name: "Contact Grid",
    screenshotLight: "img/screenshots/content-contact-grid.png",
    screenshotDark: "img/screenshots/content-contact-grid-dark.png",
    link: "/content-contact-grid",
    new: false,
  },
  {
    name: "Contact Details",
    screenshotLight: "img/screenshots/content-contact.png",
    screenshotDark: "img/screenshots/content-contact-dark.png",
    link: "/content-contact",
    new: false,
  },
  {
    name: "Bills List",
    screenshotLight: "img/screenshots/content-bills-list.png",
    screenshotDark: "img/screenshots/content-bills-list-dark.png",
    link: "/content-bills-list",
    new: false,
  },
  {
    name: "Bills Grid",
    screenshotLight: "img/screenshots/content-bills-grid.png",
    screenshotDark: "img/screenshots/content-bills-grid-dark.png",
    link: "/content-bills-grid",
    new: false,
  },
  {
    name: "Invoices List",
    screenshotLight: "img/screenshots/content-invoices-list.png",
    screenshotDark: "img/screenshots/content-invoices-list-dark.png",
    link: "/content-invoices-list",
    new: false,
  },
  {
    name: "Invoices Grid",
    screenshotLight: "img/screenshots/content-invoices-grid.png",
    screenshotDark: "img/screenshots/content-invoices-grid-dark.png",
    link: "/content-invoices-grid",
    new: false,
  },
  {
    name: "Invoice",
    screenshotLight: "img/screenshots/content-invoice.png",
    screenshotDark: "img/screenshots/content-invoice-dark.png",
    link: "/content-invoice",
    new: false,
  },
  {
    name: "Events",
    screenshotLight: "img/screenshots/content-events.png",
    screenshotDark: "img/screenshots/content-events-dark.png",
    link: "/content-events",
    new: false,
  },
  {
    name: "Social Feed",
    screenshotLight: "img/screenshots/content-feed.png",
    screenshotDark: "img/screenshots/content-feed-dark.png",
    link: "/content-feed",
    new: false,
  },
  {
    name: "Project List",
    screenshotLight: "img/screenshots/content-project-list.png",
    screenshotDark: "img/screenshots/content-project-list-dark.png",
    link: "/content-project-list",
    new: false,
  },
  {
    name: "Project Grid",
    screenshotLight: "img/screenshots/content-project-grid.png",
    screenshotDark: "img/screenshots/content-project-grid-dark.png",
    link: "/content-project-grid",
    new: false,
  },
  {
    name: "Project",
    screenshotLight: "img/screenshots/content-project.png",
    screenshotDark: "img/screenshots/content-project-dark.png",
    link: "/content-project",
    new: false,
  },
  {
    name: "Segments",
    screenshotLight: "img/screenshots/content-crm-segments.png",
    screenshotDark: "img/screenshots/content-crm-segments-dark.png",
    link: "/content-crm-segments",
    new: false,
  },
  {
    name: "Kanban Board",
    screenshotLight: "img/screenshots/content-crm-board.png",
    screenshotDark: "img/screenshots/content-crm-board-dark.png",
    link: "/content-crm-board",
    new: false,
  },
  {
    name: "Deal Details",
    screenshotLight: "img/screenshots/content-crm-deal.png",
    screenshotDark: "img/screenshots/content-crm-deal-dark.png",
    link: "/content-crm-deal",
    new: false,
  },
  {
    name: "Forum Home",
    screenshotLight: "img/screenshots/content-forum-index.png",
    screenshotDark: "img/screenshots/content-forum-index-dark.png",
    link: "/content-forum-index",
    new: false,
  },
  {
    name: "Forum Channel",
    screenshotLight: "img/screenshots/content-forum-channel.png",
    screenshotDark: "img/screenshots/content-forum-channel-dark.png",
    link: "/content-forum-channel",
    new: false,
  },
  {
    name: "Forum Topic",
    screenshotLight: "img/screenshots/content-forum-topic.png",
    screenshotDark: "img/screenshots/content-forum-topic-dark.png",
    link: "/content-forum-topic",
    new: false,
  },
  {
    name: "Email Inbox",
    screenshotLight: "img/screenshots/content-inbox.png",
    screenshotDark: "img/screenshots/content-inbox-dark.png",
    link: "/content-inbox",
    new: false,
  },
  {
    name: "Widgets",
    screenshotLight: "img/screenshots/content-widgets-data.png",
    screenshotDark: "img/screenshots/content-widgets-data-dark.png",
    link: "/content-widgets-data",
    new: false,
  },
  {
    name: "Apex Charts",
    screenshotLight: "img/screenshots/charts-apex.png",
    screenshotDark: "img/screenshots/charts-apex-dark.png",
    link: "/charts-apex",
    new: false,
  },
  {
    name: "Horizontal Form",
    screenshotLight: "img/screenshots/content-form-1.png",
    screenshotDark: "img/screenshots/content-form-1-dark.png",
    link: "/content-form-1",
    new: false,
  },
  {
    name: "Vertical Form",
    screenshotLight: "img/screenshots/content-form-2.png",
    screenshotDark: "img/screenshots/content-form-2-dark.png",
    link: "/content-form-2",
    new: false,
  },
  {
    name: "Page Placeholder",
    screenshotLight: "img/screenshots/content-placeholder.png",
    screenshotDark: "img/screenshots/content-placeholder-dark.png",
    link: "/content-placeholder",
    new: false,
  },
  {
    name: "UI Elements",
    screenshotLight: "img/screenshots/elements.png",
    screenshotDark: "img/screenshots/elements-dark.png",
    link: "/elements",
    new: false,
  },
  {
    name: "Signup",
    screenshotLight: "img/screenshots/auth-signup.png",
    screenshotDark: "img/screenshots/auth-signup-dark.png",
    link: "/auth-signup",
    new: false,
  },
  {
    name: "Login",
    screenshotLight: "img/screenshots/auth-login.png",
    screenshotDark: "img/screenshots/auth-login-dark.png",
    link: "/auth-login",
    new: false,
  },
  {
    name: "Forgot",
    screenshotLight: "img/screenshots/auth-forgot.png",
    screenshotDark: "img/screenshots/auth-forgot-dark.png",
    link: "/auth-forgot",
    new: false,
  },
  {
    name: "Error 404",
    screenshotLight: "img/screenshots/404.png",
    screenshotDark: "img/screenshots/404-dark.png",
    link: "/404",
    new: false,
  },
];

export function initRenderDemos() {
  return {
    screenshots: demos,
  };
}
